# Generated by Django 5.1.5 on 2026-03-24 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('max_properties', models.PositiveIntegerField(default=3)),
                ('max_images_per_property', models.PositiveIntegerField(default=5)),
                ('badge_label', models.CharField(max_length=50)),
                ('highlighted_home', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdvertiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertiser_type', models.CharField(choices=[('agency', 'Inmobiliaria'), ('owner', 'Particular')], default='owner', max_length=20)),
                ('visible_name', models.CharField(max_length=140)),
                ('business_name', models.CharField(blank=True, max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advertiser_profile', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advertisers', to='accounts.plan')),
            ],
            options={
                'ordering': ['-plan__priority', 'visible_name'],
            },
        ),
    ]
