# Generated by Django 5.1.5 on 2026-03-24 16:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ARS', 'ARS')], default='USD', max_length=3)),
                ('operation_type', models.CharField(choices=[('sale', 'Venta'), ('rent', 'Alquiler')], max_length=10)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Departamento'), ('land', 'Terreno'), ('shop', 'Local'), ('office', 'Oficina'), ('garage', 'Cochera'), ('country_house', 'Quinta'), ('warehouse', 'Galpón')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('zone', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=180)),
                ('latitude', models.DecimalField(decimal_places=6, default=Decimal('-34.603722'), max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=Decimal('-58.381592'), max_digits=9)),
                ('square_meters', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=0)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('garage', models.BooleanField(default=False)),
                ('patio', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('age', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('paused', 'Pausada'), ('reserved', 'Reservada'), ('sold', 'Vendida'), ('rented', 'Alquilada')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.advertiserprofile')),
            ],
            options={
                'ordering': ['-advertiser__plan__priority', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('phone', 'Teléfono'), ('website', 'Sitio web')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_clicks', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('position', models.PositiveIntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'zone'], name='properties__city_caf4e5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['operation_type', 'property_type'], name='properties__operati_da47cc_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['state', 'published_at'], name='properties__state_a91f0c_idx'),
        ),
    ]
